# Generated by Django 3.2.25 on 2025-02-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_playlist_table_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_table',
            name='content',
        ),
    ]
