# Generated by Django 3.2.25 on 2025-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_complaint_table_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_table',
            name='content',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
