# Generated by Django 3.2.25 on 2025-03-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_complaint_table_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='liked_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.song_table')),
            ],
        ),
    ]
